"""Added new ghl id in the agent table

Revision ID: 4b633c5704c6
Revises: 77961c8327a8
Create Date: 2026-01-27 22:20:20.199398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b633c5704c6'
down_revision: Union[str, Sequence[str], None] = '77961c8327a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ghl_id is now included in the initial migration (77961c8327a8)
    # This migration is a no-op to maintain migration history
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ghl_id is now included in the initial migration (77961c8327a8)
    # This migration is a no-op to maintain migration history
    pass
    # ### end Alembic commands ###
